<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?> - Admin Pusat POLBAN</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
            line-height: 1.4;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #1e3c72;
            padding-bottom: 20px;
        }
        
        .header h1 {
            color: #1e3c72;
            margin-bottom: 5px;
            font-size: 24px;
        }
        
        .header h2 {
            color: #2a5298;
            margin-bottom: 10px;
            font-size: 18px;
        }
        
        .header p {
            margin: 5px 0;
            color: #666;
            font-size: 14px;
        }
        
        .summary-section {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
            border-left: 5px solid #1e3c72;
        }
        
        .summary-title {
            color: #1e3c72;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 15px;
            text-align: center;
        }
        
        .summary-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        
        .summary-item {
            display: table-row;
        }
        
        .summary-label {
            display: table-cell;
            padding: 8px;
            font-weight: bold;
            width: 40%;
            border-bottom: 1px solid #ddd;
        }
        
        .summary-value {
            display: table-cell;
            padding: 8px;
            border-bottom: 1px solid #ddd;
            text-align: right;
            font-weight: bold;
            color: #1e3c72;
        }
        
        .breakdown-section {
            margin-bottom: 30px;
        }
        
        .breakdown-title {
            color: #1e3c72;
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 10px;
            border-bottom: 2px solid #1e3c72;
            padding-bottom: 5px;
        }
        
        .breakdown-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        .breakdown-table th,
        .breakdown-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        
        .breakdown-table th {
            background-color: #1e3c72;
            color: white;
            font-weight: bold;
            text-align: center;
        }
        
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 12px;
        }
        
        .data-table th,
        .data-table td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }
        
        .data-table th {
            background-color: #1e3c72;
            color: white;
            font-weight: bold;
            text-align: center;
        }
        
        .data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        
        .kategori-roda-dua { color: #27ae60; font-weight: bold; }
        .kategori-roda-empat { color: #3498db; font-weight: bold; }
        .kategori-sepeda { color: #9b59b6; font-weight: bold; }
        .kategori-kendaraan-umum { color: #f39c12; font-weight: bold; }
        
        .bahan-bakar-bensin { color: #e74c3c; font-weight: bold; }
        .bahan-bakar-diesel { color: #34495e; font-weight: bold; }
        .bahan-bakar-listrik { color: #f1c40f; font-weight: bold; }
        .bahan-bakar-non-bbm { color: #27ae60; font-weight: bold; }
        
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        @media print {
            body { margin: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1><?= $title ?></h1>
        <h2>Politeknik Negeri Bandung</h2>
        <p>UI GreenMetric Transportation Statistics Report</p>
        <p><strong>Generated by:</strong> <?= esc($user['nama_lengkap']) ?> | <strong>Date:</strong> <?= $generated_at ?></p>
    </div>

    <!-- Summary Statistics -->
    <div class="summary-section">
        <div class="summary-title">RINGKASAN STATISTIK TRANSPORTASI</div>
        
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-label">Total Kendaraan Terdaftar:</div>
                <div class="summary-value"><?= number_format($summary_stats['total_vehicles']) ?> Unit</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Total Entry Data:</div>
                <div class="summary-value"><?= number_format($summary_stats['total_entries']) ?> Record</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Petugas Security Aktif:</div>
                <div class="summary-value"><?= $summary_stats['total_officers'] ?> Orang</div>
            </div>
        </div>
    </div>

    <!-- Category Breakdown -->
    <?php if (!empty($summary_stats['category_breakdown'])): ?>
    <div class="breakdown-section">
        <div class="breakdown-title">BREAKDOWN PER KATEGORI KENDARAAN</div>
        <table class="breakdown-table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Kategori Kendaraan</th>
                    <th>Total Unit</th>
                    <th>Persentase</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($summary_stats['category_breakdown'] as $index => $category): ?>
                    <tr>
                        <td style="text-align: center;"><?= $index + 1 ?></td>
                        <td><?= esc($category['kategori_kendaraan']) ?></td>
                        <td style="text-align: center; font-weight: bold;"><?= number_format($category['total']) ?></td>
                        <td style="text-align: center;">
                            <?= number_format(($category['total'] / $summary_stats['total_vehicles']) * 100, 1) ?>%
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php endif; ?>

    <!-- Fuel Type Breakdown -->
    <?php if (!empty($summary_stats['fuel_breakdown'])): ?>
    <div class="breakdown-section">
        <div class="breakdown-title">BREAKDOWN PER JENIS BAHAN BAKAR</div>
        <table class="breakdown-table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Jenis Bahan Bakar</th>
                    <th>Total Unit</th>
                    <th>Persentase</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($summary_stats['fuel_breakdown'] as $index => $fuel): ?>
                    <tr>
                        <td style="text-align: center;"><?= $index + 1 ?></td>
                        <td><?= esc($fuel['jenis_bahan_bakar']) ?></td>
                        <td style="text-align: center; font-weight: bold;"><?= number_format($fuel['total']) ?></td>
                        <td style="text-align: center;">
                            <?= number_format(($fuel['total'] / $summary_stats['total_vehicles']) * 100, 1) ?>%
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php endif; ?>

    <!-- Detailed Data Table -->
    <?php if (!empty($transport_stats)): ?>
    <div class="page-break"></div>
    <div class="breakdown-section">
        <div class="breakdown-title">DATA DETAIL TRANSPORTASI</div>
        <table class="data-table">
            <thead>
                <tr>
                    <th width="5%">No</th>
                    <th width="20%">Periode</th>
                    <th width="18%">Kategori Kendaraan</th>
                    <th width="15%">Jenis Bahan Bakar</th>
                    <th width="12%">Jumlah Total</th>
                    <th width="20%">Petugas Input</th>
                    <th width="10%">Tanggal Input</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($transport_stats as $index => $row): ?>
                    <tr>
                        <td style="text-align: center;"><?= $index + 1 ?></td>
                        <td><?= esc($row['periode']) ?></td>
                        <td class="kategori-<?= strtolower(str_replace(' ', '-', $row['kategori_kendaraan'])) ?>">
                            <?= esc($row['kategori_kendaraan']) ?>
                        </td>
                        <td class="bahan-bakar-<?= strtolower(str_replace('-', '-', $row['jenis_bahan_bakar'])) ?>">
                            <?= esc($row['jenis_bahan_bakar']) ?>
                        </td>
                        <td style="text-align: center; font-weight: bold;">
                            <?= number_format($row['jumlah_total']) ?>
                        </td>
                        <td><?= esc($row['petugas_nama']) ?></td>
                        <td style="text-align: center;"><?= date('d/m/Y H:i', strtotime($row['created_at'])) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php endif; ?>

    <div class="footer">
        <p><strong>Laporan Statistik Transportasi Kampus</strong></p>
        <p>Dokumen ini digenerate secara otomatis oleh Sistem UI GreenMetric POLBAN</p>
        <p>© <?= date('Y') ?> Politeknik Negeri Bandung - Admin Pusat</p>
        <p><em>Data ini siap diserahkan kepada Tim UI GreenMetric untuk evaluasi dan penilaian</em></p>
    </div>

    <script>
        // Auto print when page loads
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>